language: c
os: linux
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
# Blacklist branches for which not to run the CI (e.g. documentation branch)
branches:
  except:
    - gh-pages
git:
  depth: false
  quiet: true
addons:
  # Load the requirements for the formatting check
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-format-5.0
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.11"
     - PRETTYNAME="Arduino TR-064 Library"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
 
before_install:
   # Download the install script for the Arduino library
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   # Load the requirements for the formatting check
   - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py
install:
   - arduino --install-library "ConfigManager"

script:
   # Run formatting check
   - python run-clang-format.py -r .
   # Run tests for both plattforms
   - build_platform esp8266
   - build_platform esp32
 
# Generate and deploy documentation
after_success:
  # Currently not doing anything
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  # Now create doxy documentation
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
